### ISSUE TITLE
No alive nodes found in your cluster on after 2.2.0 update

### ISSUE THREAD

**Issue by azhard4int** [ongr-io/ElasticsearchDSL#167]
Hi,

After upgrading from the elasticsearch-dsl 2.1.2 to 2.2.0, we are receiving the No alive nodes found in your cluster. We reverted back and it is working fine.

Is something changed on the version release? we are also using shield along with our ES node.

Regards,

**Comment by saimaz** [comment]
Hi @azhard4int,

Thanks for the feedback. This is quite interesting. 

The changes are very minimal. 
- MatchAllQuery return was changed to \std class instead of empty array
- Functional tests were introduced to test query executions on 2.4 and 5.0. Currently 2.2.0 version is tested on both elasticsearch versions, you can see it in travis: https://travis-ci.org/ongr-io/ElasticsearchDSL/builds/175022384
- `elasticsearch/elasticsearch:5.0` was added to the require-dev dependencies. Maybe you are installing composer with dev and that's how elasticsearch native client is upgraded. Because your error looks familiar that is used elasticsearch-php 5.0 version with elasticsearch 2.x database.

Can you provide:
- elasticsearch version
- elasticsearch-php version from composer
