### ISSUE TITLE
doc page link 404

### ISSUE THREAD

**Issue by zhmm** [ongr-io/ElasticsearchDSL#320]
Documentation page in https://github.com/ongr-io/ElasticsearchDSL/blob/master/docs/index.md
Build Queries link https://github.com/ongr-io/ElasticsearchDSL/blob/master/docs/Query/index.md opened 404

**Comment by TonyVlcek** [comment]
I did a bit of digging and I found that the `index.md` file was removed in e1de4d0d7bc58d0b947ad7085ed1eabbedb0cdf9 by @einorler 

I wanted to make a PR returning it to the project, but then again, it was probably removed for a reason since that commit reorganizes a lot of other doc files. I'm just starting to use this library, so I don't (yet) feel knowledgeable enough to fix the links or re-introduce the index.md page.

These are my two cents, hope it helps. I might come back to this once I'm more familiar with the project :+1:
