### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by event15** [ongr-io/ElasticsearchDSL#332]
At the moment, the project has 31 issues and several PR. Anyone else involved in this project?

**Comment by ilvalerione** [comment]
I published a PR recently that was also released, so the project should be active, but I can confirm you that it seams really slow in moving tasks forward.

I didn't clear understand if this is a strategy to keep the repo well reviewed or it isn't actively maintained.

It could be a good opportunity for owners to clarify their context.

**Comment by bcremer** [comment]
This lib is actively used by https://github.com/shopware and https://github.com/sulu. Maybe a few people from those communities can step up and form a community maintained version.

ping @alexander-schranz and @keulinho

**Comment by alexander-schranz** [comment]
Hello some weeks ago we from @sulu decided to fork the Projects as it is an important dependency for our [SuluArticleBundle](https://github.com/sulu/suluarticlebundle):

The forks are available here:

 - https://github.com/handcraftedinthealps/elasticsearchdsl
 - https://github.com/handcraftedinthealps/elasticsearchbundle (here we are only maintaining the 5.x branch because we are only using that one in sulu it still supports elasticsearch 5, 6 and 7)

The forks supports Symfony 5.

I want to say I really appreciate the work of @saimaz and I know its hard to maintain alone such a library. In our case it was just to important dependency that we could not wait for some fixes or changes for the response of him.

**Comment by event15** [comment]
I am asking because I am looking for a similar tool to use production in the company in which I work. There are several tools that have a similar effect (but I wasn't satisfied with them), but this project is the only one that is complete. 

At least it seems so. In addition, it supports version 7 elasticsearch.

**Comment by event15** [comment]
> * https://github.com/handcraftedinthealps/elasticsearchdsl
> The forks supports Symfony 5.

Can your forks be used as "framework agnostic"?

**Comment by alexander-schranz** [comment]
@event15

> I am asking because I am looking for a similar tool to use production in the company in which I work.

What I can say from my side I'm not happy about the [elasticsearch-bundle](https://github.com/ongr-io/elasticsearchbundle) and how it works (we have very special cases with inheritance where the bundle did make many problems).
But if you only use the [ElasticsearchDSL](https://github.com/ongr-io/ElasticsearchDSL) I can say nothing against that @saimaz did really good work with it and did keep it really simple 👍  and I had never big problems or issues with it.

> Can your forks be used as "framework agnostic"?

Not sure what you mean with "framework agnostic" but the `handcraftedinthealps/elasticsearch-dsl` package is registered as composer packages and will correctly replace the original package if any third party require it because of the [replace](https://github.com/handcraftedinthealps/ElasticsearchDSL/blob/1eda87a533fa93c7e9386adeee055342747d8938/composer.json#L41) feature of [composer](https://getcomposer.org/doc/04-schema.md#replace). You will not run into any conflicts if you require it, it will just install the handcraftedinthealps package instead of ongr aslong as somebody requires the new package.

**Comment by event15** [comment]
Everything in your fork is great, but I can't report issues. Is it going to change in the future?

**Comment by alexander-schranz** [comment]
@event15 basically we maintain compatibility between symfony, php and elasticsearch versions, but if you have any improvements feel free to create a Pull Request.
